### ISSUE TITLE
Plan for uploading the code

### ISSUE THREAD

**Issue by eunzihong** [YujiaLiu76/point2cad#1]
Hi,

Thank you for the great work that reconstructs CAD models from the given point cloud. I and my colleagues recently came across your work and got inspired by it, and trying to check out how the code works.
So I wonder when you're able to upload the code.

You can reach me out with my email, [eunji.hong@kaist.ac.kr](mailto:eunji.hong@kaist.ac.kr)
Thank you.

Eunji Hong.

**Comment by phongbreezy** [comment]
I'm also eager to see the code and result with my own data. 
Thanks for your great efforts so far.

**Comment by toshas** [comment]
Source code has been released; thanks for your interest!
