### ISSUE TITLE
Sharing weights of ParSeNet

### ISSUE THREAD

**Issue by yilinliu77** [YujiaLiu76/point2cad#3]
Hi Yujia,

Thanks for sharing the code! 

I noticed that the weight of ParSeNet is no longer available. I couldn't find it in the ParSeNet repository. Can you kindly share the two weights files with an additional link?

Thanks in advance!

**Comment by DietmarGrabowski** [comment]
Hi, in ParSeNet  the version of PyTorch is 1.2 and i want to load the parsenet_no_normals.pth from your link.
I get: RuntimeError: ./logs/pretrained_models/parsenet_no_normals.pth is a zip archive (did you mean to use torch.jit.load()?)
and with torch.jit.load() i get: 
File "/root/miniconda3/envs/parsenet/lib/python3.6/site-packages/torch/jit/__init__.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: version_number <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:131, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 1. Your PyTorch installation may be too old.
