### ISSUE TITLE
docker run point2cad error

### ISSUE THREAD

**Issue by wl8915** [YujiaLiu76/point2cad#5]
（1）follow your script
    ‘docker run -it --rm --gpus "device=$CUDA_VISIBLE_DEVICES" -v .:/work/point2cad toshas/point2cad:v1 python -m point2cad.main’
     i get this message：
            “docker: Error response from daemon: create .: volume name is too short, names should be at least two alphanumeric characters. See 'docker run --help'.”
（2）change script
   ‘docker run -it --rm --gpus "device=$CUDA_VISIBLE_DEVICES" -v /pyy/point2cad toshas/point2cad:v1 python -m point2cad.main’
        .:work --> pyy , my project name is pyy
    i get this message：
        “
        groupadd: GID '0' already exists
        useradd: group 'usergroup' does not exist
        error: failed switching to "user": unable to find user user: no matching entries in passwd file
        ”
Please tell me how to solve this problem or how to run this program.
Thanks。

**Comment by ShnitzelKiller** [comment]
I don't understand how you fixed this. The modified command does not fix the problem for me. I have the same error
```
groupadd: GID '0' already exists
useradd: group 'usergroup' does not exist
error: failed switching to "user": unable to find user user: no matching entries in passwd file
```

EDIT: I am on Windows, and I fixed this by running the command in WSL instead of my windows shell.
