### ISSUE TITLE
GT Segmentation input failure！

### ISSUE THREAD

**Issue by wl8915** [YujiaLiu76/point2cad#6]
![point2cad_failure](https://github.com/YujiaLiu76/point2cad/assets/66483620/8b715225-f099-48ca-987e-700aba084af6)
I entered the point cloud segmentation result for GT. 
Why does this result appear? 
What is your solution?

Looking forward to your reply.

**Comment by YujiaLiu76** [comment]
Hi, the issue you're seeing happens when the geometric relationships between the surfaces in the model aren't conducive to forming intersections as expected. To fix this, try removing triangles that are far from your input point cloud to enhance accuracy.
