### ISSUE TITLE
Mesh coordinates

### ISSUE THREAD

**Issue by lakiet1609** [YujiaLiu76/point2cad#8]
Hello,

After I have implemented the point2cad, then I found out that after reconstructed the mesh from raw point cloud input. The coordinate of mesh and the point clouds are different. The coordinate of the mesh does not remain the same as the initial point cloud. So does it affect the predicted reconstruction parameters ? 

Or u can tell me the way to calculate the transformation matrix to turn the reconstructed mesh back into initial input point clouds coordinate ?

**Comment by toshas** [comment]
You would have to save the transformation obtained here and undo it in the end: https://github.com/YujiaLiu76/point2cad/blob/main/point2cad/generate_segmentation.py#L30
